name: (Client) Deploy demo to gh-pages

on:
  push:
    branches:
      - main
    paths:
      - 'client/android/**'
      - 'client/ios/**'
      - 'client/lib/**'
      - 'client/linux/**'
      - 'client/macos/**'
      - 'client/!test/**'
      - 'client/web/**'
      - 'client/windows/**'
      - 'client/.metadata'
      - 'client/pubspec*'

jobs:
  build-and-deploy:
    # Setup part
    name: Deploy on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./client
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: ${{ matrix.flutter_path }}
        key: ${{ runner.os }}-flutter
        restore-keys: |
          ${{ runner.OS }}-flutter-
          ${{ runner.OS }}-
    - name: Use Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
      working-directory: ${{env.working-directory}}
    # End of setup
    - name: Build
      run: |
        flutter config --enable-web
        flutter build web --release
      working-directory: ${{env.working-directory}}
    - name: Remove base-tag in index.html
      run: sed -i 's/<base href="\/">//g' build/web/index.html
      working-directory: ${{env.working-directory}}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ${{env.working-directory}}/build/web
