name: (Server) Lint all packages of Query Wizard

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - '!release/**'

jobs:
  lint:
    # Setup part
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./server
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [ '5.0.x' ]
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Cache NuGet packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
          ${{ github.workspace }}/.packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
          ${{ runner.OS }}-
    # End of setup
    - name: Lint
      run: |
        chmod +x ./cibuild.sh
        ./cibuild.sh
      working-directory: ${{env.working-directory}}
